package com.rkbapps.makautsgpaygpacalculator.db.entity

import androidx.room.Entity
import androidx.room.PrimaryKey


/**
 * Represents a GPA (Grade Point Average) and its corresponding percentage.
 * This class is an Entity for the Room database.
 *
 * @property id The unique identifier for this GPA-percentage entry. Auto-generated by the database.
 * @property gpa The Grade Point Average value.
 * @property percentage The calculated percentage equivalent of the GPA.
 * @property isFavorite A boolean flag indicating whether this GPA-percentage entry is marked as a favorite. Defaults to false.
 * @property timeStamps The timestamp indicating when this entry was created or last modified, in milliseconds since the Unix epoch. Defaults to the current system time.
 */
@Entity
data class GpaPercentage(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    val gpa: Double,
    val percentage: Double,

    val isFavorite: Boolean = false,

    val timeStamps: Long = System.currentTimeMillis()

)