package com.rkbapps.makautsgpaygpacalculator.db.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents the yearly marks for a student.
 *
 * This entity is used to store the marks and related information for a specific academic year.
 * It includes details for both odd and even semesters, as well as overall yearly calculations.
 *
 * @property id The unique identifier for the yearly marks record. Auto-generated by the database.
 * @property oddSemGpa The Grade Point Average (GPA) for the odd semester.
 * @property evenSemGpa The Grade Point Average (GPA) for the even semester.
 * @property oddSemSubjects The number of subjects in the odd semester.
 * @property evenSemSubjects The number of subjects in the even semester.
 * @property evenSemPercentage The percentage obtained in the even semester.
 * @property oddSemPercentage The percentage obtained in the odd semester.
 * @property oddSemObtainedMarks The total marks obtained in the odd semester.
 * @property evenSemObtainedMarks The total marks obtained in the even semester.
 * @property oddSemTotalMarks The total possible marks for the odd semester.
 * @property evenSemTotalMarks The total possible marks for the even semester.
 * @property totalObtainedMarks The total marks obtained throughout the year (odd + even semester).
 * @property totalMarks The total possible marks for the entire year (odd + even semester).
 * @property totalPercentage The overall percentage obtained for the year.
 * @property isFavourite A boolean flag indicating whether this yearly marks record is marked as a favorite.
 * @property timeStamp The timestamp indicating when this record was created or last updated, in milliseconds.
 */
@Entity
data class YearlyMarks(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    val oddSemGpa: Double = 0.0,
    val evenSemGpa: Double = 0.0,

    val oddSemSubjects: Int = 0,
    val evenSemSubjects: Int = 0,

    val evenSemPercentage: Double = 0.0,
    val oddSemPercentage: Double = 0.0,

    val oddSemObtainedMarks: Double = 0.0,
    val evenSemObtainedMarks: Double = 0.0,

    val oddSemTotalMarks: Int = 0,
    val evenSemTotalMarks: Int = 0,

    val totalObtainedMarks: Double = 0.0,
    val totalMarks: Int = 0,
    val totalPercentage: Double = 0.0,

    var isFavourite: Boolean = false,

    val timeStamp: Long = System.currentTimeMillis()
)